a,b = input("enter 2 numbers : ").split()
print("before conversion")
print(type(a))
print(type(b))
a = int(a)
b = int(b)
print("after conversion")
print(type(a))
print(type(b))
print("product is : ",a*b)
print("sum is = ",a+b)